### ISSUE TITLE
fail to decode message

### ISSUE THREAD

**Issue by wangxin1999** [DAI-Lab/SteganoGAN#41]
I'm afraid this is the expected behavior: SteganoGAN goal is to encode messages into images and afterwards decode the messages from those images, but decoding messages from images generated by other tools is not within the scope of this project.  i was troubled with this problem for almost 1 month,i asked many friends of mine to solve this problem until them all found this problem

**Comment by jatindarkumar12** [comment]
hello sir 
i want to ask that
how to train this model on gpu cause when i send the model named "steganogan " to my gpu using .to(device)
it give error like steganogan has no "to" object
can you please guide us that how to train this model on gpu
looking forward to hear something positive from your side
