### ISSUE TITLE
Decode statement throws out error with png image

### ISSUE THREAD

**Issue by sharmaprakhar** [DAI-Lab/SteganoGAN#47]
* SteganoGAN version or git commit:
* Python version (output of `python --version`):
* Pip version (output of `pip --version`):
* PyTorch version (output of `python -c "import torch; print(torch.__version__)"`):
* Operating System:

### Description

Describe what you were trying to get done.
- Encode and decode a jpg and a png image
Tell us what happened, what went wrong, and what you expected to happen.
- encode works fine but decode throws out an error. The dependencies are mentioned within the post
### What I Did
- I made a quick fix to uitls.py in function starting line 34 

from : 
> ints.append(int(''.join([str(bit) for bit in byte]), 2))

To:

> ints.append(int(''.join([str(int(bit)) for bit in byte]), 2))

```
Paste (all) the command(s) you ran and the output.
If there was a crash, please include the traceback here.

Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy, torch
>>> print("numpy:", numpy.__version__)
numpy: 1.16.4
>>> print("torch:", torch.__version__)
torch: 1.2.0
>>> 

```

**Comment by csala** [comment]
Hello @sharmaprakhar 

Thanks for reporting this and for the suggested changes. Unfortunately, it is not clear from your description what the actual error is.

Would you mind editing the issue and adding to the "What I did" section the exact commands that you executed and the outputs that you obtained, including the error traceback?

**Comment by guidefreitas** [comment]
Hello, got an error too when decoding an png image. Details:

`ERROR: invalid literal for int() with base 2: 'TrueTrueFalseFalseFalseTrueTrueTrue'`

**Comment by pvk-developer** [comment]
> Hello, got an error too when decoding an png image. Details:
> 
> `ERROR: invalid literal for int() with base 2: 'TrueTrueFalseFalseFalseTrueTrueTrue'`
> 
> -v (verbose) didn't add any additional info.

Hello @guidefreitas, I have faced this problem recently. Would you mind checking out the `torch` version?
`SteganoGAN` must use is the `1.0.0` and I have faced the problem with higher `torch` versions. We will make a new release shortly in order to limit the `torch` version (as it's already in master).

**Comment by pvk-developer** [comment]
I'm closing this issue as we capped outside libraries, see  #54 and #50 , that fixes those kind of issues.
