### ISSUE TITLE
Issue in installing torch

### ISSUE THREAD

**Issue by sanjailal** [DAI-Lab/SteganoGAN#48]
* SteganoGAN version or git commit: 0.1.2
* Python version (output of `python --version`): 3.7.3
* Pip version (output of `pip --version`): 19.3.1
* Operating System: Windows

### Description

Unable to install torch version 1.0.0

### What I Did

I just tried installing steganogan using pip

```
pip install steganogan
ERROR: Could not find a version that satisfies the requirement torch>=1.0.0 (from steganogan) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.0.0 (from steganogan)
```

**Comment by pvk-developer** [comment]
Hello @sanjailal thank you for opening this issue, as the error states, `torch` couldn't be installed.

In windows we recommend you to install the package as shown on the pytorch website, briefly, use the following command `pip3 install torch===1.0.0 torchvision===0.2.1 -f https://download.pytorch.org/whl/torch_stable.html`. This will download and install `torch===1.0.0` which was used for developing `SteganoGAN`.

Once  you have installed `torch` just go ahead and execute `pip install steganogan`, this time the installation should finish with no errors as the requierement is satisfied. **Bear in mind** to install it in the same virtualenv if you are using one.

Also, I have faced the following problem when executing `SteganoGAN`:
`ImportError: DLL load failed: The specified module could not be found.`
If you face the same problem just install the following `C++` package in your system. https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Let us know if this helped you to fix this problem.

**Comment by sanjailal** [comment]
When I tried the following command I still get this same error
```
ERROR: Could not find a version that satisfies the requirement torch===1.1.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch===1.1.0
```

**Comment by pvk-developer** [comment]
> When I tried the following command I still get this same error
> 
> ```
> ERROR: Could not find a version that satisfies the requirement torch===1.1.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
> ERROR: No matching distribution found for torch===1.1.0
> ```

Hello @sanjailal, 
Would you mind answering me the following questions:
- Are you using a virtualenv ?
- If you are using `virtualenv` is it only for `SteganoGAN` or you have other software installed ?
- Could you run `pip freeze` and post the results here in order to see your dependencies ?

**Comment by sanjailal** [comment]
I used the same command. Anyways I switched to Linux where it works seamlessly. Thank you for your support.
