### ISSUE TITLE
Cap Pillow and other dependencies

### ISSUE THREAD

**Issue by pvk-developer** [DAI-Lab/SteganoGAN#50]
There have been some updates to `Pillow` which makes `Torchvision` to fail trying to import `PILLOW_VERSION` from `PIL`.

**Comment by hugovk** [comment]
There's now a new release of torchvision (0.5.0) that works with the newest Pillow version (7.0.0).

* https://github.com/pytorch/vision/releases/tag/v0.5.0
* https://github.com/pytorch/vision/issues/1712

An alternative to https://github.com/DAI-Lab/SteganoGAN/pull/52 is updating the torchvision pin from 0.2.1 to 0.5.0.

**Comment by pvk-developer** [comment]
> There's now a new release of torchvision (0.5.0) that works with the newest Pillow version (7.0.0).
> 
> * https://github.com/pytorch/vision/releases/tag/v0.5.0
> * [pytorch/vision#1712](https://github.com/pytorch/vision/issues/1712)
> 
> An alternative to #52 is updating the torchvision pin from 0.2.1 to 0.5.0.

Hi @hugovk  and thank you for your anwser. I will check out if `SteganoGAN` is working properly with that version of `torchvision` and if everything is okay I will proceed to update it to `torchvision==0.5.0` .

**Comment by hugovk** [comment]
You can also now upgrade to Pillow 7.1.0+, which reintroduced `PILLOW_VERSION` to allow projects some more time to update.

https://pillow.readthedocs.io/en/stable/releasenotes/7.1.0.html#pillow-version-constant
