### ISSUE TITLE
AttributeError: 'Adam' object has no attribute 'defaults'

### ISSUE THREAD

**Issue by nihit2809** [DAI-Lab/SteganoGAN#90]
* SteganoGAN version or git commit: Latest Stable
* Python version (output of `python --version`): Tried with 3.6,3.7,3.10
* Pip version (output of `pip --version`): default for the above python versions
* PyTorch version (output of `python -c "import torch; print(torch.__version__)"`): Tried with 2.0.0 & 1.13.1, couldn't use 1.0.0 as it is not available anymore to download
* Operating System: Tried on both Ubuntu and Windows 11

### Description

On running:

from steganogan import SteganoGAN
steganogan = SteganoGAN.load(architecture='basic')

Getting an error:

[/usr/local/lib/python3.9/dist-packages/torch/optim/optimizer.py](https://localhost:8080/#) in __setstate__(self, state)
    212             self._optimizer_step_post_hooks = OrderedDict()
    213         self._patch_step_function()  # To support multiprocessing pickle/unpickle
--> 214         self.defaults.setdefault('differentiable', False)
    215 
    216     def __repr__(self):

AttributeError: 'Adam' object has no attribute 'defaults'

Tried it in both colab and local notebook, but returns the same error.

### What I Did

!pip install steganogan
from steganogan import SteganoGAN
steganogan = SteganoGAN.load(architecture='basic')

## The complete error

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-4-a883da0b0023>](https://localhost:8080/#) in <cell line: 1>()
----> 1 steganogan = SteganoGAN.load(architecture='basic')

4 frames
[/usr/local/lib/python3.9/dist-packages/steganogan/models.py](https://localhost:8080/#) in load(cls, architecture, path, cuda, verbose)
    362                 'Please provide either an architecture or a path to pretrained model.')
    363 
--> 364         steganogan = torch.load(path, map_location='cpu')
    365         steganogan.verbose = verbose
    366 

[/usr/local/lib/python3.9/dist-packages/torch/serialization.py](https://localhost:8080/#) in load(f, map_location, pickle_module, weights_only, **pickle_load_args)
    813             except RuntimeError as e:
    814                 raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
--> 815         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    816 
    817 

[/usr/local/lib/python3.9/dist-packages/torch/serialization.py](https://localhost:8080/#) in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
   1041     unpickler = UnpicklerWrapper(f, **pickle_load_args)
   1042     unpickler.persistent_load = persistent_load
-> 1043     result = unpickler.load()
   1044 
   1045     deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)

[/usr/local/lib/python3.9/dist-packages/torch/optim/adam.py](https://localhost:8080/#) in __setstate__(self, state)
     50 
     51     def __setstate__(self, state):
---> 52         super().__setstate__(state)
     53         for group in self.param_groups:
     54             group.setdefault('amsgrad', False)

[/usr/local/lib/python3.9/dist-packages/torch/optim/optimizer.py](https://localhost:8080/#) in __setstate__(self, state)
    212             self._optimizer_step_post_hooks = OrderedDict()
    213         self._patch_step_function()  # To support multiprocessing pickle/unpickle
--> 214         self.defaults.setdefault('differentiable', False)
    215 
    216     def __repr__(self):

AttributeError: 'Adam' object has no attribute 'defaults'

**Comment by aeschylus** [comment]
I also get this in a variety of environments. The library needs a thorough updating.

**Comment by aeschylus** [comment]
One thing that helped was installing an earlier version of `pytorch` and `torchvision`

**Comment by subyun** [comment]
Same here, and I found
`pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`
Hope this helps you

**Comment by nihit2809** [comment]
Thanks a lot. These changes worked out flawlessly.
